FROM python:2.7
RUN pip install gunicorn -i https://pypi.douban.com/simple
COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt -i https://pypi.douban.com/simple
WORKDIR /code
CMD mkdir -p /data && \
    celery -A app.celeryInstance worker --loglevel=info --detach && \
    gunicorn -c gunicorn.cfg run_webhook:app
